### ISSUE TITLE
Optimizing away repeated decoders and/or sparse transforms

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo#738]
I have ensembles `A` and `B`, which are both high dimension. 

Between them I create a few thousand connections, all from a single dimension in `A` to a single dimension in `B`. Many of these connections are coming from the same dimension in `A`.

`A` cannot be an ensemble array. And the connections all have different synapses, so the connections cannot be combined.

This is very slow (it wouldn't even build after an hour), because each connection is recomputing the same decoders, and using a large transform matrix with a single 1.

It was possible to speed up the build process ~100x, simply by creating an array of scalar nodes between `A` and `B`, and channelling each dimension of `A` to each "proxy" node. This reduces the number of decoder optimizations to the dimensionality of `A`, and the transforms to `B` become column vectors instead of matrices.

The same process could be repeated for `B`, to convert all the column vectors into scalars, again with the cost of an extra matrix. This does not help for my case though, since no connections are to the same dimensions in `B`, and so there are no repeated column vectors to consolidate at a proxy.

Automating these sorts of optimization procedures will of course be challenging. But the benefits are potentially enormous in some cases.

**Comment by tcstewar** [comment]
Weird...  are we really recomputing ```pinv(dot(A.T, A))``` for every connection?  I thought that was kept in the cache....  or are we only caching decoders now?  In Nengo 1.4 we only computed that inverse once per ensemble, cached it, and then every decoder was just computed with just a matrix multiply from that (I don't think we even bothered caching the decoders).

Maybe the right approach is to set up some hooks into the cache system so that the solvers can make use of it as appropriate?

**Comment by arvoelke** [comment]
Part of it could be that each connection had a different scalar on the transform. Not sure if decoder caching takes that into account, or if it's pre-multiplied.

Not sure if these sorts of optimizations can be solved at the decoder caching level, though. Whether this sort of consolidation is advantageous requires global knowledge of whether there will be connections that use similar decoders that can essentially share the same signal (both for building [memory and number of optimizations], and for simulating [shape and number of multiplies]).

**Comment by tcstewar** [comment]
> Not sure if these sorts of optimizations can be solved at the decoder caching level, though. Whether this sort of consolidation is advantageous requires global knowledge of whether there will be connections that use similar decoders that can essentially share the same signal (both for building [memory and number of optimizations], and for simulating [shape and number of multiplies]).

For at least some of the solvers it looks like there's feasible things to cache...  I was thinking of this sort of thing in the cholesky solver:

```
        L = np.linalg.cholesky(G)
        L = np.linalg.inv(L.T)
        x = np.dot(L, np.dot(L.T, b))
```

That result of ```np.linalg.inv``` could be cached as an intermediate variable, and if that was the solver being used in your case then it looks like that would solve the problem.

However, looking at the other solvers, there doesn't seem to always be those sorts of nice intermediate variables (or at least I'm not seeing them).  In that case, it strikes me that this could all be addressed by the builder, consolidating together all the Connections from an Ensemble that use the same Solver, concatenating together all the targets that have different Connection.functions, then just calling the Solver once, getting the superset of decoders, and then doing the transform stuff to get the final decoders for all the Connections.  

That said, it's not clear to me how to fit that sort of logic into the current system....

**Comment by jgosmann** [comment]
> Weird... are we really recomputing pinv(dot(A.T, A)) for every connection?

We shouldn't, but #677 still isn't merged, so the current implementation probably slows things down. Even the improved cache might not be beneficial in this case. Further possible improvements might be:

* Detect if decoders are a scaled version of already computed decoders.
* Keep a buffer cached objects in memory (at the moment everything is written to the hard disk and read back in from there).

**Comment by jgosmann** [comment]
> We shouldn't, but #677 still isn't merged, so the current implementation probably slows things down.

This was ambiguous. What I mean is, I don't think we're recomputing `pinv(dot(A.T, A))` for every connection. #677 improves the cache performance, but is not related to whether we recompute `pinv(dot(A.T, A))` or not.

**Comment by jgosmann** [comment]
From the discussion of today's dev meeting:

I don't think the current cache implementation fixes this:
1. The cache is only activated when a seed is set.
2. The cache key is based on the connection's rng state. That will be different for each connection as long as not the same seed is set for each individual connection.

However the rng might not be relevant in all cases. It is used to generate eval points, but these are included in the cache key already, so that the rng is not needed in this case. The only other usage of the rng might be in the solver. So we could not include it in the cache key for solvers not actually dependent on the rng state. Maybe it even makes sense to never include it? Even if the solver depends on the rng state (e.g. randomized SVD), the result should work for other connections if only the rng state changes. But it could give unexpected results: The decoders for two connections with different seeds could be the same.

**Comment by drasmuss** [comment]
After some more discussion today, our thinking that this is a relatively unusual use case (making thousands of connections between the same two ensembles), and in general it would be better to make changes so that users don't need to do that, rather than making that use case more efficient. I think this originally came up as a way to implement heterogeneous synapses (https://github.com/nengo/nengo/pull/788), so our thinking is that the dev effort would be better spent directly supporting that (which we plan to do, see https://github.com/nengo/nengo/issues/1636), and then people wouldn't even need to create these thousands of semi-redundant connections.
